# Use root/example as user/password credentials
version: '3.1'
services:

#  db-mariadb:
#    image: mariadb:10
#    restart: always
#    environment:
#      MARIADB_ROOT_PASSWORD: example
#
#  adminer:
#    image: adminer:4.8.0
#    restart: always
#    ports:
#      - "8080:8080"

  web:
    image: php:7.4.23-apache
    container_name: my-apache-php-app
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html

